document.addEventListener('DOMContentLoaded', function () {
    const churchList = document.getElementById('church-list');
    const lastUpdate = document.getElementById('last-update');
    const searchInput = document.getElementById('search');
    const prevPageButton = document.getElementById('prev-page');
    const nextPageButton = document.getElementById('next-page');
    const pageInfo = document.getElementById('page-info');

    let churches = [];
    let currentPage = 1;
    const itemsPerPage = 8;

    // ---------- THEME PALETTE LOGIC (inserted here) ----------
    const seasonPalettes = {
        "Tempo da Quaresma": {
            accent: "#7c3aed", accentDark: "#5b21b6", accentText: "#ffffff",
            headerStops: ["#1f2937", "#4c1d95", "#7c3aed"]
        },
        "Tríduo Pascal": {
            accent: "#dc2626", accentDark: "#991b1b", accentText: "#ffffff",
            headerStops: ["#2b0b0b", "#b91c1c", "#ef4444"]
        },
        "Tempo Pascal": {
            accent: "#f59e0b", accentDark: "#b45309", accentText: "#092040",
            headerStops: ["#2b1f0b", "#f59e0b", "#fbbf24"]
        },
        "Tempo do Advento": {
            accent: "#5b21b6", accentDark: "#3b0f80", accentText: "#ffffff",
            headerStops: ["#07113a", "#3b0f80", "#5b21b6"]
        },
        "Tempo do Natal": {
            accent: "#10b981", accentDark: "#047857", accentText: "#ffffff",
            headerStops: ["#062018", "#047857", "#10b981"]
        },
        "Tempo Comum": {
            accent: "#059669", accentDark: "#046c4a", accentText: "#ffffff",
            headerStops: ["#062018", "#046c4a", "#059669"]
        }
    };

    const monthPalettes = {
        0: seasonPalettes["Tempo do Natal"],   // Jan
        1: seasonPalettes["Tempo Comum"],      // Feb
        2: seasonPalettes["Tempo da Quaresma"],// Mar
        3: seasonPalettes["Tempo Pascal"],     // Apr
        4: seasonPalettes["Tempo Pascal"],     // May
        5: seasonPalettes["Tempo Comum"],      // Jun
        6: seasonPalettes["Tempo Comum"],      // Jul
        7: seasonPalettes["Tempo Comum"],      // Aug
        8: seasonPalettes["Tempo Comum"],      // Sep
        9: seasonPalettes["Tempo do Advento"], // Oct
        10: seasonPalettes["Tempo do Advento"],// Nov
        11: seasonPalettes["Tempo do Natal"]   // Dec
    };

    function applyPalette(palette) {
        if (!palette) return;
        // set CSS variables for easy future refactor
        document.documentElement.style.setProperty('--theme-accent', palette.accent);
        document.documentElement.style.setProperty('--theme-accent-dark', palette.accentDark);
        document.documentElement.style.setProperty('--theme-accent-text', palette.accentText);

        // header overlay (absolute inset-0 element inside header)
        const headerOverlay = document.querySelector('header .absolute.inset-0');
        if (headerOverlay) {
            const stops = palette.headerStops || [palette.accentDark, palette.accent];
            headerOverlay.style.background = `linear-gradient(90deg, ${stops.join(', ')})`;
            headerOverlay.style.opacity = '0.18';
            headerOverlay.style.mixBlendMode = 'overlay';
        }

        // liturgical season badge
        const badge = document.getElementById('liturgical-season');
        if (badge) {
            badge.style.backgroundColor = palette.accent;
            badge.style.color = palette.accentText;
            badge.style.border = `1px solid ${palette.accentDark}`;
        }

        // main CTA button (the Leituras do dia anchor)
        const cta = document.querySelector('a[href="leitura-diaria.html"]');
        if (cta) {
            cta.style.backgroundColor = palette.accent;
            cta.style.color = palette.accentText;
            cta.style.borderColor = palette.accentDark;
        }

        // schedule item left borders (these are generated by renderChurches)
        document.querySelectorAll('.schedule-item').forEach(item => {
            item.style.borderLeft = `4px solid ${palette.accent}`;
        });

        // icon color
        const churchIcon = document.querySelector('.fas.fa-church');
        if (churchIcon) churchIcon.style.color = palette.accent;
    }

    function pickPaletteBySeasonOrMonth(seasonText) {
        if (seasonText && seasonPalettes[seasonText]) {
            return seasonPalettes[seasonText];
        }
        const now = new Date();
        return monthPalettes[now.getMonth()] || seasonPalettes["Tempo Comum"];
    }

    // convenience: call after the #liturgical-season is available or after dynamic rendering
    function applyPaletteFromDOM() {
        const seasonElem = document.getElementById('liturgical-season');
        const seasonText = seasonElem ? (seasonElem.textContent || '').trim() : '';
        const palette = pickPaletteBySeasonOrMonth(seasonText);
        applyPalette(palette);
    }
    // ---------- END THEME PALETTE LOGIC ----------

     // Criação do elemento de referência no header
    const header = document.createElement('div');
    document.body.insertBefore(header, document.body.firstChild);
    document.body.insertBefore(header, document.body.firstChild);

    // Load data from JSON file
    fetch('data/churches.json')
        .then(response => {
            if (!response.ok) {
                throw new Error('Arquivo de dados não encontrado.');
            }
            return response.json();
        })
        .then(data => {
            churches = data.churches;
            console.log(churches);
            lastUpdate.textContent = `Última atualização: ${data.collection_date}`;

            if (churches.length === 0) {
                churchList.innerHTML = '<div class="text-center text-gray-600">Nenhuma paróquia encontrada.</div>';
                return;
            }

            // Render all churches initially
            renderChurches(churches);
            applyPaletteFromDOM(); // <-- ensure theme applied after initial render
            updatePagination();

            // Configure search
            searchInput.addEventListener('input', function () {
                const term = this.value.toLowerCase();
                const result = churches.filter(church =>
                    church.name.toLowerCase().includes(term) ||
                    (church.address && church.address.toLowerCase().includes(term)) ||
                    church.communities.some(community =>
                        community.name.toLowerCase().includes(term) ||
                        (community.address && community.address.toLowerCase().includes(term)) ||
                        community.schedule.some(schedule => schedule.toLowerCase().includes(term))
                ));

                currentPage = 1; // Reset to first page on new search
                renderChurches(result);
                applyPaletteFromDOM(); // <-- theme new results
                updatePagination();
            });

            // Pagination
            prevPageButton.addEventListener('click', () => {
                if (currentPage > 1) {
                    currentPage--;
                    renderChurches(churches);
                    applyPaletteFromDOM(); // <-- theme after pagination change
                    updatePagination();
                }
            });

            nextPageButton.addEventListener('click', () => {
                if (currentPage < Math.ceil(churches.length / itemsPerPage)) {
                    currentPage++;
                    renderChurches(churches);
                    applyPaletteFromDOM(); // <-- theme after pagination change
                    updatePagination();
                }
            });
        })
        .catch(error => {
            churchList.innerHTML = `<div class="text-center text-red-600">Erro ao carregar os dados: ${error.message}</div>`;
            console.error('Erro:', error);
        });

    function renderChurches(list) {
        if (list.length === 0) {
            churchList.innerHTML = '<div class="text-center text-gray-600">Nenhuma paróquia encontrada com esses termos.</div>';
            return;
        }

        churchList.innerHTML = '';

        // Use a grid layout for the cards
        churchList.className = 'grid grid-cols-1 md:grid-cols-2 gap-6';

        // Calculate items for the current page
        const startIndex = (currentPage - 1) * itemsPerPage;
        const endIndex = startIndex + itemsPerPage;
        const paginatedItems = list.slice(startIndex, endIndex);

        paginatedItems.forEach(church => {
            const card = document.createElement('div');
            card.className = 'church-card bg-white rounded-lg shadow-md p-6 hover:shadow-lg transition-all dark:bg-gray-700 dark:text-white';

            // Church name - FIRST based on the HTML inspector
            const name = document.createElement('h2');
            name.className = 'church-name text-2xl font-bold text-blue-900 mb-4 dark:text-blue-300';
            name.textContent = church.name;
            card.appendChild(name);

            // Church address - SECOND based on the HTML inspector
            if (church.address && church.address.trim()) {
                const address = document.createElement('p');
                address.className = 'church-address text-gray-700 mb-4 dark:text-gray-300';
                address.textContent = church.address.trim();
                card.appendChild(address);
            }

            // Church link - THIRD based on the HTML inspector
            if (church.link) {
                const link = document.createElement('a');
                link.className = 'church-link text-blue-500 hover:text-blue-700 mb-4 inline-block dark:text-blue-400';
                link.href = church.link;
                link.target = '_blank';
                link.textContent = 'Visitar página oficial';
                card.appendChild(link);
            }

            // Communities container
            const communitiesContainer = document.createElement('div');
            communitiesContainer.className = 'communities-container space-y-4';

            if (church.communities && church.communities.length > 0) {
                church.communities.forEach((community, index) => {
                    const communityDiv = document.createElement('div');
                    communityDiv.className = 'community';

                    // Community address (if available)
                    if (community.address && community.address.trim()) {
                        const communityAddress = document.createElement('p');
                        communityAddress.className = 'community-address text-gray-700 mb-2 dark:text-gray-300';
                        communityAddress.textContent = community.address.trim();
                        communityDiv.appendChild(communityAddress);
                    }

                    // Community name
                    const communityName = document.createElement('h3');
                    communityName.className = 'community-name text-xl font-semibold text-gray-800 mb-2 dark:text-gray-200';
                    communityName.textContent = `${index + 1}. ${community.name}`;
                    communityDiv.appendChild(communityName);

                    // Schedule container
                    const scheduleDiv = document.createElement('div');
                    scheduleDiv.className = 'schedule space-y-2';

                    if (community.schedule && community.schedule.length > 0) {
                        community.schedule.forEach(schedule => {
                            if (schedule && schedule.trim()) {
                                // Split the schedule into individual lines
                                const scheduleLines = schedule.split('\n');
                                scheduleLines.forEach(line => {
                                    if (line.trim()) {
                                        const scheduleItem = document.createElement('div');
                                        scheduleItem.className = 'schedule-item bg-gray-50 p-3 rounded-lg border-l-4 border-blue-500 dark:bg-gray-600 dark:border-blue-400 dark:text-gray-200';
                                        scheduleItem.textContent = line.trim();
                                        scheduleDiv.appendChild(scheduleItem);
                                    }
                                });
                            }
                        });
                    } else {
                        const noSchedule = document.createElement('div');
                        noSchedule.className = 'schedule-item bg-gray-50 p-3 rounded-lg border-l-4 border-yellow-500 dark:bg-gray-600 dark:border-yellow-400 dark:text-gray-200';
                        noSchedule.textContent = 'Visite a página oficial para informações referentes a esta comunidade.';
                        scheduleDiv.appendChild(noSchedule);
                    }

                    communityDiv.appendChild(scheduleDiv);
                    communitiesContainer.appendChild(communityDiv);
                });
            } else {
                const noCommunity = document.createElement('div');
                noCommunity.className = 'community text-gray-600 dark:text-gray-400 mt-4';
                noCommunity.textContent = 'Esta paróquia não possui comunidades cadastradas.';
                communitiesContainer.appendChild(noCommunity);
            }

            card.appendChild(communitiesContainer);
            churchList.appendChild(card);
        });

        // After we've injected dynamic nodes, ensure the palette is applied to them
        applyPaletteFromDOM();
    }

    function updatePagination() {
        const filteredChurches = churches.filter(church => {
            const term = searchInput.value.toLowerCase();
            return church.name.toLowerCase().includes(term) ||
                (church.address && church.address.toLowerCase().includes(term)) ||
                church.communities.some(community =>
                    community.name.toLowerCase().includes(term) ||
                    (community.address && community.address.toLowerCase().includes(term)) ||
                    community.schedule.some(schedule => schedule.toLowerCase().includes(term))
            );
        });
        
        const totalPages = Math.ceil(filteredChurches.length / itemsPerPage);
        pageInfo.textContent = `Página ${currentPage} de ${totalPages || 1}`;
        prevPageButton.disabled = currentPage === 1;
        nextPageButton.disabled = currentPage === totalPages || totalPages === 0;
    }
});
